# Generated by Django 2.2.4 on 2019-08-19 08:01

import bestapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestapp', '0003_examcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LoginClass',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('dob', models.CharField(default=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('choice_one', models.CharField(max_length=200)),
                ('choice_two', models.CharField(max_length=200)),
                ('choice_three', models.CharField(max_length=200)),
                ('choice_four', models.CharField(max_length=200)),
                ('choice_five', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='StudentReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(default=False, max_length=20)),
                ('fatherName', models.CharField(max_length=100)),
                ('motherName', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=30)),
                ('schoolName', models.CharField(max_length=30)),
                ('schoolAddress', models.CharField(max_length=200)),
                ('homeAddress', models.CharField(max_length=200)),
                ('state', models.CharField(default=False, max_length=30)),
                ('examMode', models.CharField(max_length=10)),
                ('aadharNumber', models.CharField(max_length=15)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('emailID', models.EmailField(max_length=40)),
                ('personPhoto', models.ImageField(blank=True, null=True, upload_to=bestapp.models.new_file_name)),
                ('signaturePhoto', models.ImageField(blank=True, null=True, upload_to=bestapp.models.new_file_name)),
                ('username', models.CharField(default=False, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='ApplicationFormClass',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice_four',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice_one',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice_three',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice_two',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question',
        ),
        migrations.AddField(
            model_name='questions',
            name='question_no',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examcode',
            name='code',
            field=models.CharField(max_length=15),
        ),
    ]
