# Generated by Django 2.2.4 on 2019-08-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestapp', '0004_auto_20190819_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
