# Generated by Django 2.2.4 on 2019-08-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestapp', '0005_questions_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='option1',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
