# Generated by Django 2.2.4 on 2019-08-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestapp', '0011_questions_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='exam_code',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
